### ISSUE TITLE
Add i18n to Next.JS frontend

### ISSUE THREAD

**Issue by losolio** [losol/eventuras-front#12]
## Description

Add i18n to Next.JS frontend to allow for multiple languages. The default language in the source vode is English `en-US`. 

In addition to English, Norwegian `nb-NO` should be supported. 

## Tasks

-   [x] Add i18n to Next.JS frontend
-   [x] Add support for Norwegian `nb-NO` with fallback to English `en-US`. The translations will be done by project owner, only needed a few example translations to get started.

## Acceptance criteria
- [x] next-translate is used as a framework for i18n. See [next-translate](https://github.com/aralroca/next-translate)
-  [x] The default language in the source code is English `en-US`
- [x] The default locale for site is read from an environment variable. If no environment variable is set, the default locale is `en-US`.
- [x] The default locale for site is set to Norwegian `nb-NO` in the environment variable.
-  ~~The site is available in English `en-US` and Norwegian `nb-NO` after project owner has provided translations~~
- [x] [Next js Internationalization (i18n) Routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalization) of type Sub-path Routing should used for locale detection. The locale is detected from the first part of the path. If no locale is detected, the default locale is used.

**Comment by losolio** [comment]
done 🥳
